"""Markdown export as a pure function.

Per plan R11 / R12: ``render_analysis_to_md`` is a single pure function that
turns an ``AnalysisJob`` into a Markdown string; no I/O, no abstractions,
no plugin layer. ``build_filename`` produces the ``seoserper-...-.md`` name.

Failure sections render a one-line Chinese diagnostic so users see "why"
without clicking through (Design Principles: 失败状态内含诊断信息).
"""

from __future__ import annotations

import base64
import re
from datetime import datetime, timezone

from seoserper.models import (
    AnalysisJob,
    FailureCategory,
    PAAQuestion,
    RelatedSearch,
    Suggestion,
    SurfaceName,
    SurfaceStatus,
)

SURFACE_HEADINGS: dict[SurfaceName, str] = {
    SurfaceName.SUGGEST: "Suggestions",
    SurfaceName.PAA: "People Also Ask",
    SurfaceName.RELATED: "Related Searches",
}

SURFACE_EMPTY_MESSAGES: dict[SurfaceName, str] = {
    SurfaceName.SUGGEST: "_No suggestions returned._",
    SurfaceName.PAA: "_No People Also Ask questions returned._",
    SurfaceName.RELATED: "_No related searches returned for this query._",
}

FAILURE_DIAGNOSTIC_ZH: dict[FailureCategory, str] = {
    FailureCategory.BLOCKED_RATE_LIMIT: "被限流（SerpAPI 配额用尽 或 Suggest 限流）—— 建议等 quota 重置或 5 分钟后重试",
    FailureCategory.SELECTOR_NOT_FOUND: "响应结构未匹配（provider schema drift 或 HTML 拦截页）",
    FailureCategory.NETWORK_ERROR: "网络错误 —— 检查连接 / API key",
}


def render_analysis_to_md(analysis: AnalysisJob) -> str:
    """Render an AnalysisJob as Markdown.

    Branches on ``analysis.render_mode``:

    - ``"full"`` (default, pre-pivot + post-flip jobs) — emits the original
      Appendix A layout with 3 sections and 3 status_* frontmatter keys.
    - ``"suggest-only"`` — emits a single Suggestions section, omits
      status_paa / status_related from frontmatter, and adds ``render_mode``
      so downstream readers can distinguish scope.

    ``render_mode`` is the single frontmatter line inserted immediately after
    ``country`` and before ``timestamp`` — position is fixed so the three
    golden fixtures receive a uniform diff shape.
    """
    ts_iso = _iso_utc(analysis.started_at)
    ts_human = _human_utc(analysis.started_at)
    is_suggest_only = analysis.render_mode == "suggest-only"

    frontmatter: list[str] = [
        "---",
        f"query: {analysis.query}",
        f"language: {analysis.language}",
        f"country: {analysis.country}",
        f"render_mode: {analysis.render_mode}",
        f"timestamp: {ts_iso}",
        f"source_suggest: {analysis.source_suggest}",
    ]
    if not is_suggest_only:
        frontmatter.append(f"source_serp: {analysis.source_serp}")
    frontmatter.append(
        f"status_suggestions: {_status_value(analysis, SurfaceName.SUGGEST)}"
    )
    if not is_suggest_only:
        frontmatter.extend(
            [
                f"status_paa: {_status_value(analysis, SurfaceName.PAA)}",
                f"status_related: {_status_value(analysis, SurfaceName.RELATED)}",
            ]
        )
    frontmatter.extend(["---", "", f"# {_escape_md_inline(analysis.query)}", ""])

    body: list[str] = []
    surfaces_to_render = (
        (SurfaceName.SUGGEST,)
        if is_suggest_only
        else (SurfaceName.SUGGEST, SurfaceName.PAA, SurfaceName.RELATED)
    )
    for surface_name in surfaces_to_render:
        body.extend(_render_section(analysis, surface_name))
        body.append("")

    footer = ["---", "", f"_Generated by SEOSERPER · {ts_human}_", ""]

    return "\n".join(frontmatter + body + footer)


def build_filename(analysis: AnalysisJob) -> str:
    """Produce the `seoserper-<slug>-<lang>-<country>-<YYYYMMDD-HHmm>.md` filename."""
    slug = slugify(analysis.query)
    stamp = _filename_timestamp(analysis.started_at)
    return f"seoserper-{slug}-{analysis.language}-{analysis.country}-{stamp}.md"


def slugify(text: str, max_len: int = 60) -> str:
    """ASCII-safe slug. Falls back to base64 of utf-8 bytes for non-ASCII queries."""
    lowered = text.lower()
    replaced = re.sub(r"[^a-z0-9]+", "-", lowered)
    collapsed = re.sub(r"-+", "-", replaced).strip("-")
    if collapsed:
        return collapsed[:max_len].strip("-") or "query-empty"

    # All-special or all-non-ASCII input — hash the raw bytes for uniqueness.
    encoded = (
        base64.urlsafe_b64encode(text.encode("utf-8"))
        .decode("ascii")
        .rstrip("=")
        .lower()
    )
    if not encoded:
        return "query-empty"
    return f"q-{encoded[:10]}"


# --- internals ---------------------------------------------------------------


def _status_value(analysis: AnalysisJob, name: SurfaceName) -> str:
    surface = analysis.surfaces.get(name)
    return surface.status.value if surface else SurfaceStatus.RUNNING.value


def _render_section(analysis: AnalysisJob, name: SurfaceName) -> list[str]:
    heading = SURFACE_HEADINGS[name]
    surface = analysis.surfaces.get(name)
    if surface is None or surface.status == SurfaceStatus.RUNNING:
        return [f"## {heading}", "", "_Pending._"]

    if surface.status == SurfaceStatus.EMPTY:
        return [f"## {heading}", "", SURFACE_EMPTY_MESSAGES[name]]

    if surface.status == SurfaceStatus.FAILED:
        diagnostic = FAILURE_DIAGNOSTIC_ZH.get(
            surface.failure_category, "未知失败"
        )
        return [
            f"## {heading}",
            "",
            f"_{heading} 获取失败: {diagnostic}_",
        ]

    # status == OK
    count = len(surface.items)
    out = [f"## {heading} ({count})", ""]
    if count == 0:
        out.append(SURFACE_EMPTY_MESSAGES[name])
        return out

    for item in surface.items:
        out.append(_render_item(name, item))
    return out


def _render_item(name: SurfaceName, item: object) -> str:
    if name == SurfaceName.SUGGEST:
        assert isinstance(item, Suggestion)
        return f"{item.rank}. {_escape_md_inline(item.text)}"
    if name == SurfaceName.RELATED:
        assert isinstance(item, RelatedSearch)
        return f"{item.rank}. {_escape_md_inline(item.query)}"
    # PAA
    assert isinstance(item, PAAQuestion)
    bold = f"{item.rank}. **{_escape_md_inline(item.question)}**"
    if item.answer_preview:
        return bold + "\n   " + _escape_md_inline(item.answer_preview)
    return bold


# Escape the minimal set of markdown metacharacters that cause inline drift
# when pasted into Notion / 飞书 / VS Code previews. We intentionally do NOT
# escape `#` (heading markers only matter at start of line) or `-` (common
# in queries; dashes at line start aren't heading-forming mid-paragraph).
_INLINE_ESCAPE_PATTERN = re.compile(r"([\\*_`\[\]])")


def _escape_md_inline(text: str) -> str:
    return _INLINE_ESCAPE_PATTERN.sub(r"\\\1", text)


def _iso_utc(stamp: str) -> str:
    """Normalize SQLite 'YYYY-MM-DD HH:MM:SS' to ISO 8601 UTC."""
    dt = _parse_stamp(stamp)
    if dt is None:
        return stamp or ""
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def _human_utc(stamp: str) -> str:
    dt = _parse_stamp(stamp)
    if dt is None:
        return stamp or ""
    return dt.strftime("%Y-%m-%d %H:%M UTC")


def _filename_timestamp(stamp: str) -> str:
    dt = _parse_stamp(stamp) or datetime.now(timezone.utc)
    return dt.strftime("%Y%m%d-%H%M")


def _parse_stamp(stamp: str) -> datetime | None:
    if not stamp:
        return None
    try:
        # Accept both 'YYYY-MM-DD HH:MM:SS' and ISO 8601 'YYYY-MM-DDTHH:MM:SS[+TZ]'.
        dt = datetime.fromisoformat(stamp.replace(" ", "T").rstrip("Z"))
    except ValueError:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)
